# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
