# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0023_auto_20181015_1538'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_seats', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.ScreenModel')),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
