# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='seat_class',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='ticket_price',
            field=models.IntegerField(choices=[('SILVER', 180), ('GOLD', 250), ('PLATINUM', 400)], default=0, verbose_name='Ticket Price'),
        ),
    ]
