# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20181020_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='total_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
