# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingmodel_total_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='total_amt',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='user_data',
        ),
    ]
