# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 05:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_remove_screenmodel_ticket_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_auto_20181022_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.IntegerField(choices=[('SILVER', 180), ('GOLD', 250), ('PLATINUM', 400)], default=0, verbose_name='Ticket Price')),
                ('no_seats', models.IntegerField(default=0)),
                ('total_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('s_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.ShowModel')),
                ('user_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BookingModel',
        ),
    ]
