# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 06:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20181023_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='s_detail',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='movies.ShowModel'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='ticket_price',
            field=models.IntegerField(choices=[(180, 'SILVER'), (250, 'GOLD'), (400, 'PLATINUM')], verbose_name='Ticket Price'),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='user_data',
            field=models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
