# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20181023_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='s_detail',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='total_amt',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='user_data',
        ),
    ]
