# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_remove_screenmodel_ticket_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0007_auto_20181023_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmodel',
            name='s_detail',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='movies.ShowModel'),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='total_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='user_data',
            field=models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
