# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20181023_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='ticket_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.ScreenModel'),
        ),
    ]
