# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20181025_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='s_detail',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='user_data',
        ),
        migrations.DeleteModel(
            name='ReservationModel',
        ),
    ]
