# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0013_auto_20181025_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_data', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=100)),
                ('screen', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('show_time', models.TimeField()),
                ('ticket_class', models.CharField(max_length=20)),
                ('ticket_price_per_ticket', models.IntegerField(null=True)),
                ('no_seats', models.IntegerField()),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=7)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
