# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_reservationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
