# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20181025_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationmodel',
            name='ticket_price_per_ticket',
        ),
    ]
