# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100, verbose_name='Movie Title')),
                ('m_language', models.CharField(choices=[('None', 'None'), ('Malayalam', 'M'), ('Hindi', 'H'), ('English', 'E'), ('Tamil', 'T')], default='None', max_length=20, verbose_name='Movie Language')),
                ('m_rating', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Movie IMDB Rating')),
                ('m_genre', models.CharField(choices=[('None', 'None'), ('Action', 'action'), ('Adventure', 'adventure'), ('Comedy', 'comedy'), ('Science_Fiction', 'science_fiction'), ('Crime', 'crime'), ('Drama', 'drama'), ('Epic', 'epics'), ('Horror', 'horror')], default='None', max_length=50, verbose_name='Movie Genre')),
                ('m_length', models.DecimalField(decimal_places=2, help_text='enter time in hours', max_digits=4, verbose_name='Movie length')),
                ('m_poster', models.ImageField(upload_to='media/movie_posters', verbose_name='Movie Poster')),
                ('m_trailer', models.FileField(blank='True', upload_to='media/movie_trailers', verbose_name='Movie Trailer')),
                ('m_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
