# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_showmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showmodel',
            old_name='m_status',
            new_name='s_status',
        ),
    ]
