# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20181012_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='showmodel',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
