# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_showmodel_create_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_name', models.CharField(choices=[('None', 'None'), ('pranav', 'pranav'), ('athulya', 'athulya'), ('vismaya', 'vismaya'), ('ashirvad', 'ashirvad')], default='None', max_length=100, verbose_name='Screen name')),
                ('sc_tot_seats', models.IntegerField(verbose_name='total Seats')),
                ('ticket_price_silver', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ticket Price(Silver)')),
                ('ticket_price_gold', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ticket Price(Gold)')),
                ('ticket_price_platinum', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ticket Price(Platinum)')),
                ('sc_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Screen Status')),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='m_status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Movie Status'),
        ),
        migrations.AlterField(
            model_name='showmodel',
            name='s_status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Show Status'),
        ),
    ]
