# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20181012_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenmodel',
            name='sc_name',
            field=models.CharField(max_length=100, verbose_name='Screen name'),
        ),
    ]
