# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20181012_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateField()),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='moviemodel',
            name='m_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Movie Title'),
        ),
        migrations.AddField(
            model_name='playlistmodel',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaylistMovie', to='movies.MovieModel'),
        ),
    ]
