# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20181013_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistmodel',
            name='movie',
        ),
        migrations.AlterField(
            model_name='screenmodel',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='screenmodel',
            name='sc_name',
            field=models.CharField(default='Ashirvad', max_length=100, verbose_name='Screen name'),
        ),
        migrations.DeleteModel(
            name='PlaylistModel',
        ),
    ]
