# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_moviemodel_m_poster2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_date', models.DateField()),
                ('sc_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Screen Status')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaylistMovie', to='movies.MovieModel')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlaylistScreen', to='movies.ScreenModel')),
                ('show', models.ForeignKey(default='Ashirvad', on_delete=django.db.models.deletion.CASCADE, related_name='Playlistshow', to='movies.ShowModel')),
            ],
        ),
    ]
