# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_playlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistmodel',
            name='pl_name',
            field=models.CharField(default='not specified', max_length=100, verbose_name='Playlist name'),
        ),
    ]
