# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_playlistmodel_pl_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistmodel',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Playlistshow', to='movies.ShowModel'),
        ),
    ]
