# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20181014_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistmodel',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='playlistmodel',
            name='s_date',
        ),
        migrations.RemoveField(
            model_name='playlistmodel',
            name='screen',
        ),
        migrations.RemoveField(
            model_name='playlistmodel',
            name='show',
        ),
    ]
