# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20181014_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlaylistModel',
        ),
    ]
