# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_delete_playlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='showmodel',
            name='s_date',
            field=models.DateField(default='not specified'),
        ),
        migrations.AlterField(
            model_name='screenmodel',
            name='sc_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Screen name'),
        ),
    ]
