# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-14 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_auto_20181014_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showmodel',
            name='s_date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
