# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_remove_showmodel_s_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='showmodel',
            name='movie',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='PlaylistScreen', to='movies.MovieModel'),
        ),
        migrations.AddField(
            model_name='showmodel',
            name='s_date',
            field=models.DateField(default='auto_now_add'),
        ),
        migrations.AddField(
            model_name='showmodel',
            name='s_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='showmodel',
            name='screen',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='PlaylistScreen', to='movies.ScreenModel'),
        ),
    ]
