# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20181015_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showmodel',
            name='s_date',
        ),
    ]
