# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_remove_showmodel_s_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showmodel',
            name='s_name',
        ),
    ]
