# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_auto_20181015_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenmodel',
            name='ticket_price_gold',
        ),
        migrations.RemoveField(
            model_name='screenmodel',
            name='ticket_price_platinum',
        ),
        migrations.RemoveField(
            model_name='screenmodel',
            name='ticket_price_silver',
        ),
        migrations.AddField(
            model_name='screenmodel',
            name='ticket_price',
            field=models.IntegerField(choices=[(180, 'Silver'), (250, 'gold'), (400, 'platinum')], default=0, verbose_name='ticket prices'),
        ),
    ]
