# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_auto_20181020_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenmodel',
            name='ticket_price',
        ),
    ]
