# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_auto_20181023_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenmodel',
            name='gold_price',
            field=models.IntegerField(null=True, verbose_name='gold Seat price'),
        ),
        migrations.AddField(
            model_name='screenmodel',
            name='platinum_price',
            field=models.IntegerField(null=True, verbose_name='platinum seat price'),
        ),
        migrations.AddField(
            model_name='screenmodel',
            name='silver_price',
            field=models.IntegerField(null=True, verbose_name='silver Seat price'),
        ),
    ]
