# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_auto_20181023_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenmodel',
            name='sc_tot_seats',
        ),
    ]
