# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0028_remove_screenmodel_sc_tot_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarousalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_description', models.CharField(max_length=100, verbose_name='image description')),
                ('img_carousal', models.ImageField(upload_to='media/carousal', verbose_name='Home Carousal 1')),
                ('sc_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, verbose_name='Screen Status')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='showmodel',
            name='movie',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='movies.MovieModel'),
        ),
        migrations.AlterField(
            model_name='showmodel',
            name='screen',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='movies.ScreenModel'),
        ),
    ]
